# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6f432b8f1df6bb4e792d81f7b6f6e615c6e1763cb03b180d14959fcf8cd208ad0c1a997db7257757185f3637d5042633045724f7307e01ec512f77057e7412

test:
  secret_key_base: 779c07b9046feff4e23dc8f6e8d20b92e5b0297afd5a989633079e87f9550f0147b4dffdff1c117dccfcb91cac70204823cd31bf18ed06e053cc3204278d9c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
